AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  This template setups the environment for the Snowflake SageMaker workshops.
  Author: Dylan Tong, AWS
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Repository Configurations
        Parameters:
          - pTemplatesURL
      - Label: 
          default: Snowflake Configurations
        Parameters:
          - pExternalStageBaseName
      - Label:
          default: Amazon SageMaker Studio Configurations
        Parameters:
          - pDomainName
          - pUserName
      - Label:
          default: VPC Configurations
        Parameters:
          - pVpcId
          - pSubnets
      - Label:
          default: Optional VPC Configurations
        Parameters:
          - pSecurityGroups
    ParameterLabels:
      pTemplatesURL:
        default: "Workshop Templates URL"
      pExternalStageBaseName:
        default: "[Required] Snowflake External Stage (S3 Bucket Name)"
      pDomainName:
        default: "Amazon SageMaker Studio Domain Name"
      pVpcId:
        default: "VPC" 
      pSubnets:
        default: "VPC Subnets"
      pUserName:
        default: "User Profile Name"
      pSecurityGroups:
        default: "[Optional] Security Groups"
Parameters:
  pTemplatesURL:
    Description: >-
      The S3 URL path containing the CloudFormation templates used to deploy the workshop resources.
    MinLength: 10    
    Type: String
    Default: "https://dtong-public-fileshare.s3-us-west-2.amazonaws.com/snowflake-sagemaker-workshop/src/deploy/cf/"
  pExternalStageBaseName:
    AllowedPattern: '[A-Za-z0-9-]{1,63}'
    ConstraintDescription: >-
      Maximum of 63 alphanumeric characters. Can include hyphens (-), but not spaces. Must be unique within your account
      in an AWS Region.
    Description: >-
      Must be unique. Provide a base name for an S3 bucket that will be created and used as a Snowflake external stage.
    MaxLength: 63
    MinLength: 1    
    Type: String
    Default: snowflake-sagemaker
  pDomainName:
    AllowedPattern: '[A-Za-z0-9-]{1,63}'
    ConstraintDescription: >-
      Maximum of 63 alphanumeric characters. Can include hyphens (-), but not spaces. Must be unique within your account in an
      AWS Region.
    Description: Name of the Amazon SageMaker Studio domain
    MaxLength: 63
    MinLength: 1
    Type: String
    Default: sagemaker-studio-cf-managed
  pVpcId:
    Description: Choose a VPC for SageMaker Studio
    Type: 'AWS::EC2::VPC::Id'
  pSubnets:
    Description: Choose a subnet in an availability zone supported by Amazon SageMaker.
    Type: 'List<AWS::EC2::Subnet::Id>'
  pUserName:
    AllowedPattern: '[A-Za-z0-9-]{1,20}'
    ConstraintDescription: >-
      Maximum of 63 alphanumeric characters. Can include hyphens (-), but not spaces. Must be unique within your account in 
      an AWS Region.
    Description: Provide a name for the profile that you will use to log into Amazon SageMaker Studio.
    MaxLength: 63
    MinLength: 1
    Type: String
    Default: "sagemaker-user"
  pSecurityGroups:
    Description: >- 
      This is optional. Configure your security groups for SageMaker Studio (https://docs.aws.amazon.com/sagemaker/latest/dg/onboard-vpc.html)
    Type: CommaDelimitedList
    Default: ''
Resources:
  FullKernelBuilderStack: 
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://dtong-public-fileshare.s3.us-west-2.amazonaws.com/kernel-builder/src/deploy/cf/kernel-builder-full.yml
      Parameters:
        pSolutionRepository: dtong-public-fileshare
        pWorkspaceBaseName: !Ref pExternalStageBaseName
        pDomainName: !Ref pDomainName
        pVpcId: !Ref pVpcId
        pSubnets: !Join
          - ","
          - !Ref pSubnets
        pUserName: !Ref pUserName
        pSecurityGroups: !Join
          - ","
          - !Ref pSecurityGroups
        pProjectName: workshop-kernel-builder
        pImageType: aws/codebuild/standard:5.0
        pRepoName: sagemaker-snowflake-workshop
        pKernelImageName: snowflake-workshop
  WorkshopResourceStack:
    DependsOn: 
      - FullKernelBuilderStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - "${TemplatesURL}workshop-base.yml"
        - TemplatesURL: !Ref pTemplatesURL
      Parameters:
        pExternalStageBucketName: !GetAtt      
          - FullKernelBuilderStack
          - Outputs.Workspace
Outputs:
  ExternalStageName: 
    Value: !GetAtt      
      - FullKernelBuilderStack
      - Outputs.Workspace