AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  This template setups the environment for the Snowflake SageMaker workshops.
  Author: Dylan Tong, AWS
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Repository Configurations
        Parameters:
          - pTemplatesURL
      - Label: 
          default: Snowflake Configurations
        Parameters:
          - pExternalStageBaseName
      - Label:
          default: Amazon SageMaker Studio Configurations
        Parameters:
          - pDomainId
    ParameterLabels:
      pTemplatesURL:
        default: "Workshop Templates URL"
      pExternalStageBaseName:
        default: "[Required] Snowflake External Stage (S3 Bucket Name)"
      pDomainId:
        default: "[Required] Amazon SageMaker Studio (Domain) Id"
Parameters:
  pTemplatesURL:
    Description: >-
      The S3 URL path containing the CloudFormation templates used to deploy the workshop resources.
    MinLength: 10    
    Type: String
    Default: "https://dtong-public-fileshare.s3.us-west-2.amazonaws.com/snowflake-sagemaker-workshop/src/deploy/cf/"
  pExternalStageBaseName:
    AllowedPattern: '[A-Za-z0-9-]{1,63}'
    ConstraintDescription: >-
      Maximum of 63 alphanumeric characters. Can include hyphens (-), but not spaces. Must be unique within your account
      in an AWS Region.
    Description: >-
      Must be unique. Provide a base name for an S3 bucket that will be created and used as a Snowflake external stage.
    MaxLength: 63
    MinLength: 1    
    Type: String
    Default: snowflake-sagemaker
  pDomainId:
    AllowedPattern: '[A-Za-z0-9-]{1,63}'
    ConstraintDescription: >-
      Maximum of 63 alphanumeric characters. Can include hyphens (-), but not
      spaces. Must be unique within your account in an AWS Region.
    Description: The Studio (Domain) Id of your existing Amazon SageMaker Studio environment.
    MaxLength: 63
    MinLength: 1
    Type: String
Resources:
  BuildAndPubKernelBuilderStack: 
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://dtong-public-fileshare.s3.us-west-2.amazonaws.com/kernel-builder/src/deploy/cf/kernel-builder-build-and-publish.yml
      Parameters:
        pSolutionRepository: dtong-public-fileshare
        pWorkspaceBaseName: !Ref pExternalStageBaseName
        pDomainId: !Ref pDomainId
        pProjectName: workshop-kernel-builder
        pImageType: aws/codebuild/standard:5.0
        pRepoName: sagemaker-snowflake-workshop
        pKernelImageName: snowflake-workshop
  WorkshopResourceStack:
    DependsOn: 
      - BuildAndPubKernelBuilderStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - "${TemplatesURL}workshop-base.yml"
        - TemplatesURL: !Ref pTemplatesURL
      Parameters:
        pExternalStageBucketName: !GetAtt      
          - BuildAndPubKernelBuilderStack
          - Outputs.Workspace
Outputs:
  ExternalStageName: 
    Value: !GetAtt      
      - BuildAndPubKernelBuilderStack
      - Outputs.Workspace